spring:
  datasource:
    url: jdbc:mysql://localhost:3306/any-pdf?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1

# 文件临时保存路径
file:
  path: E:\tmp\
  tmpSave: true

# openfeign目标服务
security:
  url: 127.0.0.1:9898
  serviceName: QINGYUN-SECURITY-SERVICE

# 身份凭证
client:
  clientId: qazujm12378ttqmn
  secret: -edf4lsdf89q3$c)ddddd222adfgnsnejcujmaslosallash

